[package]
name = "rust_model_core"
version = "0.1.0"
authors = ["Miaofei <ameision@hotmail.com>"]
edition = "2018"

[dependencies]
tokio = { version = "1.7.1", features = ["rt-multi-thread"] }

[lib]
path = "src/lib.rs"
crate-type = ["rlib", "dylib"]
