[package]
name = "rust_model_stdlib_toy"
version = "0.1.0"
authors = ["Miaofei <ameision@hotmail.com>"]
edition = "2018"

[dependencies]
rust_model_core = { path = "../../core" }

[lib]
path = "src/toy_type_1.rs"
crate-type = ["dylib"]
