[package]
name = "rust_model_stdlib"
version = "0.1.0"
authors = ["Miaofei <ameision@hotmail.com>"]
edition = "2018"

[dependencies]
rust_model_core = { path = "../core" }
rust_model_stdlib_toy = { path = "src/toy" }

[lib]
path = "src/lib.rs"
crate-type = ["rlib", "dylib"]
